# Generated by Django 2.2.24 on 2021-12-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211206_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Software',
            new_name='SoftwareProduct',
        ),
    ]
