# Generated by Django 2.2.24 on 2021-12-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211207_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='owner',
        ),
    ]
